# Site settings
title: Jacob Brown Personal Website
description: Jacob Brown
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jacob Brown
user_description: Computer Science student with aspirtaions to pursue a career in Software Development
user_title: Computer Science Student
email: JBrown_14@arcadia.edu
twitter_username: https://twitter.com/Sondercide_
github_username:  https://bitbucket.org/Sondercide/

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
